### ISSUE TITLE
Allowing anybody to edit, delete, and mark as spam and see admin features

### ISSUE THREAD

**Issue by IntellectProductions** [silverstripe/silverstripe-forum#120]
I don't have anybody under the moderating section of my forums and it's allowing everybody to edit, delete, and mark as spam.. I created a regular user with basic permissions, no admin rights and they are still allowed to edit, delete, and mark as spam any post.. and they can see the admin features section at the very bottom.

It seems as if the Post methods are not even being executed because I try to do a die() in them to debug the values that are being passed and the page loads perfectly fine.. it doesn't die.

**Comment by camfindlay** [comment]
Hi there @IntellectProductions , would be great if you could let me know the details to try and replicate the problem on a fresh copy of SilverStripe. I'll check it out and see if I can confirm it as a bug (or under what conditions it is a bug if it is).

**Comment by camfindlay** [comment]
@IntellectProductions closing for now, feel free to reopen if you can provide some further details around the issue. I haven't been able to reproduce on a fresh copy of the forum module against lastest SilverStripe core.

**Comment by camfindlay** [comment]
Ok I think I found the issue, the canModerate method was checking for a canEdit rather than checking if the user is an admin. Pull request on the way.

**Comment by camfindlay** [comment]
This has been fixed with #134
