### ISSUE TITLE
Posts without titles create links that cannot be clicked

### ISSUE THREAD

**Issue by Martimiz** [silverstripe/silverstripe-forum#124]
Posts without Title are accepted, but no default Title is added, which results in a post that seemingly has no link, only an author (an empty anchor with valid href in HTML). I just saw one such post appear in the SilverStripe forums and was able to reproduce it.

**Comment by camfindlay** [comment]
@Martimiz would a simple fix be to make the title a require input in the post form perhaps?

**Comment by Martimiz** [comment]
@camfindlay : sure, soo simple and it would work just fine, I guess :)

Would you want me to do the pr? (I'm not familiar with the module, but, as long as I don't need to write a test for it - or should I?)

**Comment by camfindlay** [comment]
yeah go for it. I can peer review for you :+1:

**Comment by camfindlay** [comment]
@Martimiz let me know how you are getting on with this - I actually have someone who's learning SilverStripe development who is keen to start contributing to FOSS and this could be a good bug to fix for him :) If you've already cut some code all good otherwise I'll look at getting some eyes on this and some code written :)

**Comment by Martimiz** [comment]
No, that's fine, I was planning on doing it tomorrow morning, so just go ahead :)

**Comment by camfindlay** [comment]
@Martimiz can you look at @scott1702's pull request, appears there was already code checking for this and there was an issue with the particular type of data being checked.

**Comment by Martimiz** [comment]
function PostMessageForm($addMode = false, $post = false) {
        ...
        $required = ($addMode == 'true') ? ...

This would fix the current issue :) But it might have sideeffects: 

Issue: 
$PostMessageForm(true) from within the template uses a string parameter, whereas PostMessageForm($addMode=false) expects a Boolean. 

Other conditionals do still treat $addMode as Boolean though , for instance: 

		if ($addMode && !$this->canPost()) {
 			Security::permissionFailure($this, $messageSet);
			return false;			
		}

Also the fix wouldn't work if at some point ->PostMessageForm(true) is called from code though (would it ever?). An alternative might possibly be:

    function PostMessageForm($addMode = false, $post = false) {
        $addMode = ($addMode === 'true' || $addMode === true) ? true : false; 

Ugly. But basically this is an issue where a function call from within a template can ever only have a string parameter...

**Comment by camfindlay** [comment]
what about ensuring the $addMode is cast as a boolean using the php (bool) type? 

so maybe adding 

```php
$addMode = (bool) $addMode;
```
directly after the method declaration.

**Comment by dhensby** [comment]
Adding `$addMode = (bool) $addMode;` won't case a string with value 'false' as `false`.

You'll need a manual check `if (!$addMode || strtolower($addMode) == 'false')`

**Comment by camfindlay** [comment]
good suggestion @dhensby :+1:

**Comment by scott1702** [comment]
Changed the code with @Martimiz's suggestion. Seems to solve the issue quite efficiently.

**Comment by Martimiz** [comment]
Sorry for the late response - strtolower makes sense (people might use 'True') so I'd agree with @dhensby

**Comment by scott1702** [comment]
Edited the code and I think it should be good now, thoughts appreciated :)

**Comment by camfindlay** [comment]
Any further ahead on this fix guys? I'd like to get it in to the upcoming 0.8.0 release :)

**Comment by Martimiz** [comment]
If I'm correct and this is the latest solution, then I think it still doesn't support 'False' or 'FALSE' ?

		if (!$addMode || $addMode == 'false') {
    			$addMode = false;
		}

Also, possibly off topic, would it be a good idea to have boolean params be handled by the template engine, assuming that false or true, whatever the case used, would be meant to be a boolean (especially false)?

**Comment by dhensby** [comment]
> would it be a good idea to have boolean params be handled by the template engine, assuming that false or true, whatever the case used, would be meant to be a boolean

I guess so. I'd be for enforcing quoted strings in the template. eg: 

```php
$Link(false) // equivalent to $this->Link(false);
$Link('false') // equivalent to $this->Link('false');
$Link(somerandomtext) //throws an error or warning of undefined constant
```

The only issue is that's going to be quite an upgrade pain and (perhaps) hard to justify. I do think we need to remove this mixed param type and you're suggestion of abstracting that logic of converting "true" and "false" to boolean type at the template parsing level is a nice one.

**Comment by camfindlay** [comment]
I guess going back to the original issue, We should hunt a MVP fix for stopping post without titles occurring that would be suitable for a minor point release then perhaps tackle some more fundamental architecture issues post this?

**Comment by camfindlay** [comment]
Think that #137 fixed this.
