### ISSUE TITLE
ForumHolderTest fails on MSSQL

### ISSUE THREAD

**Issue by wilr** [silverstripe/silverstripe-forum#15]
From http://open.silverstripe.org/ticket/5614

[1;31mForum Holder Test::test Get New Posts Available
Failed asserting that boolean:false is true.
[0m[31mIn line  of 

[0m<ul>PHPUnit_Framework_Assert::assertTrue()
line 141 of ForumHolderTest.php

@halkyon have you got a mssql test runner for doing dev work? Can you check this is still a problem

**Comment by camfindlay** [comment]
Travis is no longer testing this against MSSQL

**Comment by dhensby** [comment]
Travis never did but @sminnee is working on getting mssql tests running

**Comment by camfindlay** [comment]
Closing, we don't test this module against mssql any longer.
