### ISSUE TITLE
ENHANCEMENT Posts you don't have permission to reply to should be handled better

### ISSUE THREAD

**Issue by andrewandante** [silverstripe/silverstripe-forum#168]
At the moment, if you attempt to reply to a post that you cannot (eg. if only admins can reply), you are still able to click 'Reply'. Then the button changes to plain text and a silent 403 is returned. 

A better implementation would be to either remove the reply button altogether, preferably with some sort of 'This post is read-only' marker, or to return some sort of 'sorry, you don't have permission to reply to this post' on click.

**Comment by edlinklater** [comment]
@andrewandante: I can't reproduce this - are you able to give further information, such as which version of the forum module?

**Comment by dhensby** [comment]
ping @andrewandante

**Comment by andrewandante** [comment]
Hello, sorry for the tardiness. It will have been version 0.8.0. 

I was attempting to post a reply to a forum that should only have been postable by admins and core committers. However, it had been replied to already by one member because the OP hadn't made it read-only like they had intended.  Then when I went to reply, it failed in the way described. I haven't had a chance to try and reproduce locally. Will let you know if I come across anything useful.

**Comment by edlinklater** [comment]
Sorry, I've been unable to reproduce this. Please feel free to re-open with more detail if you come across it again.
