### ISSUE TITLE
ForumMemberProfile go to 404 page

### ISSUE THREAD

**Issue by Misagh90** [silverstripe/silverstripe-forum#178]
when i click on register link on forum the register page shown : "Page not found
Sorry, it seems you were trying to access a page that doesn't exist.
Please check the spelling of the URL you were trying to access and try again."

and i try it by memberprofile add-on again
but it still not working

**Comment by tractorcow** [comment]
What is the url that you were sent to , @Misagh90 ?

**Comment by edlinklater** [comment]
Hi @Misagh90, can you confirm that you are running SilverStripe 3.2? This is an issue I've also encountered with 3.2 relating to how default controller routes are handled.

**Comment by Misagh90** [comment]
@tractorcow , register url: /ForumMemberProfile/register
& profile url: /ForumMemberProfile/show/2
@edlinklater yes it's 3.2

**Comment by Misagh90** [comment]
I ask it in SilverStripe forum: http://www.silverstripe.org/community/forums/forum-module-forum/show/111335

**Comment by tractorcow** [comment]
@camfindlay mr forum module master. Any ideas as to how this is breaking?

**Comment by pozd** [comment]
You have to add this "
Director:
  rules:
    'ForumMemberProfile/$Action/$ID/$OtherID': 'ForumMemberProfile'
" to forum.yml
Cause from Silverstripe 3.2 you have to add routes manualy.

**Comment by bigbang1980** [comment]
Thank you so much, your solution worked like a charm

**Comment by Misagh90** [comment]
@pozd Thank you, it's work smooth

**Comment by camfindlay** [comment]
Thanks all, I think this relates to the security change in 3.2.0 relating to https://docs.silverstripe.org/en/3.2/changelogs/3.2.0/#api-removed-url-routing-by-controller-name

Would be great if someone could push a pull request to the module with this fix. It doesn't seem like a breaking change (just more explicitly sets the route) so can likely go onto the current stable branch (0.8) and I'll make a 0.8.1 release.

**Comment by camfindlay** [comment]
See #179 If someone can check my work and merge that would be great...

**Comment by bretuobay** [comment]
Hello, I applied the fix suggested by @pozd and the redirect works i.e it takes me to a page with the following content. 
**"If this is your first visit, you will need to register before you can post. However, you can browse all messages below.

Please logout before you register - Logout

Currently Online: There is nobody online.
"**
But when I click on the register link, it doesn't give me a registrazione form like I expected. This is my first time installing Silverstripe. Any suggestions? Thanks

**Comment by camfindlay** [comment]
Fixed in #179
