### ISSUE TITLE
Editing profile is not working

### ISSUE THREAD

**Issue by Misagh90** [silverstripe/silverstripe-forum#180]
Hi,

I'm working on Forum addon, when i edit my profile (/ForumMemberProfile/edit/1) , the fields of information does not change and save anything and only show the last information

i don't know what is wrong.

**Comment by camfindlay** [comment]
Hi @Misagh90 I have just installed a fresh copy of SilverStripe 3.2.1 and forum 0.8.1 and can not replicate this issue. I am able to visit the link mentioned and edit the profile successfully.

Can you let me know how you went about installing the module on your site?

**Comment by camfindlay** [comment]
my bad, on further inspection it appears that follow up edit do indeed have a bug. I'll be looking into this shortly, I suspect it may be again related to the custom routing in 3.2.x SilverStripe core.

**Comment by camfindlay** [comment]
So this is less a bug and more a missing feature where once logged in you probably shouldn't have to add your password again just to update your profile. So a feature might need to be written in this case.

**Comment by camfindlay** [comment]
Not a bug, current feature means you need to fill out the password to update. A new feature would need to be created to alter this and should go on master.
