### ISSUE TITLE
Selector for Subscription Uses a TD Element

### ISSUE THREAD

**Issue by gordonbanderson** [silverstripe/silverstripe-forum#182]
The selector below for subscription forces a td.replyButton into the design which seems restrictive.

```javascript
/**
		 * Subscribe / Unsubscribe button
		 */
		$("td.replyButton a.subscribe").click(function() {
            alert('clicked subscribe');
			$.post($(this).attr("href"), function(data) {
				if(data == 1) {
					$("td.replyButton a.subscribe").hide().addClass("hidden");
					$("td.replyButton a.unsubscribe").show().removeClass("hidden");
				}
			});
			return false;
		});
```

**Comment by camfindlay** [comment]
Put this against master incase users are already relying on this (as it would be a breaking change).
Will look to bundle a number of new breaking changes into a new 1.0.0 version.

**Comment by gordonbanderson** [comment]
Done, see https://github.com/silverstripe/silverstripe-forum/pull/187
