### ISSUE TITLE
What is that status of the project

### ISSUE THREAD

**Issue by SteveAzz** [silverstripe/silverstripe-forum#193]
Hello,
I really like this project and quite like the idea. I would like to start using this module in an existing silverstripe website that I have, but I have a few concerns about it. It doesn't seem to be in active development, last commit was in May and there are stale pull requests and just a lot of open issues. 

I have found bugs whilst using the module such as duplicate of titles, url not getting generated properly and probably more if I try to implement it properly.

My question is if we send bug fixes and bug reeports how quick would be the support? Now I  understand this is OSS im not expecting next day support or anything. 

Also is there any toughts on keeping developing this module?

**Comment by dhensby** [comment]
This module is actively maintained and is in use on our own silverstripe.org site to power our forum.

It is a bit buggy at the moment, but we (I) would be more than happy to accept PRs that improve the forum module
