### ISSUE TITLE
SS 4 compatible?

### ISSUE THREAD

**Issue by sparkcom** [silverstripe/silverstripe-forum#208]
Hello 

Wonder if work is being done to make it SS4 compatible

**Comment by robbieaverill** [comment]
Hey, @zanderwar has done some work to upgrade it, but it’s not something that SilverStripe Ltd is going to continue to support since we have moved to using Discourse for our forums

**Comment by sparkcom** [comment]
The official SS site use discourse. Is there any module that help to integrate Silverstripe and Discourse?
